Javascript local storage - Tiffany Brown
tiffanydbrown/c1023-code-solutions pull request #58
Opened 2023-11-10 20:11 UTC by tiffanydbrown

<img width="759" alt="Screenshot 2023-11-10 at 12 05 52 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/9e62683b-fa3d-400e-8005-49a5b3d03781">

2023-11-13 16:12 UTC, shawnkost requested changes
One change here Tiffany!

2023-11-13 16:12 UTC, shawnkost commented on javascript-local-storage/data.js
> +todos = JSON.parse(previousTodosJSON);
This should be inside an `if` statement making sure `previousTodosJSON` does not equal `null`

2023-11-13 17:00 UTC, tiffanydbrown commented
<img width="759" alt="Screenshot 2023-11-13 at 8 58 47 AM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/1ef80890-0bae-4ace-b46f-4f8a3dca314e">

2023-11-13 17:49 UTC, tiffanydbrown commented
<img width="759" alt="Screenshot 2023-11-13 at 9 47 33 AM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/85bd4e23-5d50-4925-956f-234259b2ea5a">

2023-11-20 17:11 UTC, shawnkost approved these changes
👍🏻

2023-11-20 18:17 UTC, merged