Completed es6 classes exercise. - Tiffany Brown
tiffanydbrown/c1023-code-solutions pull request #64
Opened 2023-11-21 23:18 UTC by tiffanydbrown

<img width="831" alt="Screenshot 2023-11-21 at 3 16 20 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/310a3a06-659e-4d69-8277-ad07df2c8fc3">
<img width="831" alt="Screenshot 2023-11-21 at 3 15 59 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/9022bfd0-cdc6-4cef-ab18-bb82f505aafe">
<img width="831" alt="Screenshot 2023-11-21 at 3 08 03 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/9bb43b0e-0ea7-4a5d-a09f-ed58242af008">

2023-11-21 23:22 UTC, shawnkost requested changes
Few changes here Tiffany!

2023-11-21 23:22 UTC, shawnkost commented on es6-classes/circle.js
> +  constructor(area, perimeter, radius) {
This constructor should only be receiving 1 argument, for your `radius`.

2023-11-21 23:22 UTC, shawnkost commented on es6-classes/circle.js
> +    super(area, perimeter);
Utilizing your `radius`, you need to calculate `area` & `perimeter`, and that's what you'll pass into `super`

2023-11-21 23:22 UTC, shawnkost commented on es6-classes/square.js
> +  constructor(area, perimeter, width) {
This constructor should only be receiving 1 argument, for your `radius`.

2023-11-21 23:22 UTC, shawnkost commented on es6-classes/square.js
> +    super(area, perimeter);
Utilizing your `width`, you need to calculate `area` & `perimeter`, and that's what you'll pass into `super`

2023-11-21 23:48 UTC, tiffanydbrown commented
<img width="831" alt="Screenshot 2023-11-21 at 3 46 55 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/f82ff6ff-6cb5-4bcf-86a8-0dc1a6683c7d">
<img width="831" alt="Screenshot 2023-11-21 at 3 46 35 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/2a2ddb37-f2f9-42b2-8715-dda7a407b5de">

2023-11-22 17:41 UTC, shawnkost approved these changes
👍🏻

2023-11-22 17:42 UTC, merged