Completed array methods exercise. - Tiffany Brown
tiffanydbrown/c1023-code-solutions pull request #68
Opened 2023-12-04 23:51 UTC by tiffanydbrown

<img width="1501" alt="Screenshot 2023-12-04 at 3 43 39 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/f342cd58-2fa0-4aa6-8769-8eef667f5486">

2023-12-05 00:04 UTC, shawnkost requested changes
One change here Tiffany

2023-12-05 00:04 UTC, shawnkost commented on array-methods/for-each.js
> +reversedArray.forEach((element) => console.log(element));
You should be accomplishing this without the use of a 2nd array

2023-12-05 02:52 UTC, tiffanydbrown commented
<img width="1501" alt="Screenshot 2023-12-04 at 6 51 38 PM" src="https://github.com/tiffanydbrown/c1023-code-solutions/assets/139157669/47a73dff-3b8b-443a-8371-f4bda347e63e">

2023-12-06 16:14 UTC, shawnkost approved these changes
👍🏻

2023-12-06 17:10 UTC, merged